export enum Shape {
  SMALL_SQUARE = 'SMALL_SQUARE',
  SMALL_ROUND = 'SMALL_ROUND',
  BIG_SQUARE = 'BIG_SQUARE',
  BIG_ROUND = 'BIG_ROUND',
  RECTANGLE = 'RECTANGLE',
  SQUARE = 'SQUARE',
  ROUND = 'ROUND',
  SMALL = 'SMALL',
}
