export enum SpaceItemType {
  PLAYGROUND = 'PLAYGROUND',
  RECEPTION_BAR = 'RECEPTION_BAR',
  BATHROOM = 'BATHROOM',
  STAIRS_UP = 'STAIRS_UP',
  STAIRS_DOWN = 'STAIRS_DOWN',
  EXIT_VERTICAL = 'EXIT_VERTICAL',
  EXIT_HORIZONTAL = 'EXIT_HORIZONTAL',
  WINDOW_VERTICAL = 'WINDOW_VERTICAL',
  WINDOW_HORIZONTAL = 'WINDOW_HORIZONTAL',
  NO_ITEM = 'NO_ITEM',
}
